# Generated by Django 5.0.6 on 2024-09-29 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversations',
            new_name='Conversation',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='message',
            new_name='content',
        ),
    ]
